name: "Delete old packages"
description: "Delete old packages"
author: "Solibri"
inputs:
  org-name:
    description: Organization name
    required: true
  token:
    description: Personal access token to read and delete packages
    required: true
  repo-name:
    description: Repository name
    required: true
  package-type:
    description: Package type - maven | npm | docker | container
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
